export const $groupEnum = [
   {id: "158", title: "AGC Glass Russia"},
   {id: "154", title: "Самара гис"},
   {id: "148", title: "Разработка сайта 'финансовый рентер'"},
   {id: "146", title: "Отель Артика, Витязево"},
   {id: "144", title: "Разработка ЛК инвестора и Агента"},
   {id: "140", title: "Волжский утес"},
   {id: "138", title: "Морган-групп"},
   {id: "134", title: "Шале базель, 2 гостиницы"},
   {id: "132", title: "Самаранефтепромлизинг"},
   {id: "128", title: "Consolica (Консолика) - Платформа для блогеров"},
   {id: "126", title: "7 Авеню (7 Avenue)"},
   {id: "124", title: "Нонстоп Non Stop"},
   {id: "122", title: "Vklad.ru Вклад.ру"},
   {id: "118", title: "Visit-samara.com"},
   {id: "114", title: "Модуль RESERV ошибки"},
   {id: "112", title: "Модуль RESERV доработки"},
   {id: "94", title: "Добро МФО"},
   {id: "92", title: "Эдьюфан"},
   {id: "84", title: "Богатырская слобода "},
   {id: "82", title: "Серебро севера "},
   {id: "77", title: "Ost West"},
   {id: "75", title: "Белуга (BELUGA)"},
   {id: "61", title: "samara.travel"},
   {id: "53", title: "Борапак "},
   {id: "35", title: "Некоммерческое партнёрство «Российская футбольная Премьер-Лига» "},
   {id: "33", title: "Reserv.travel "},
   {id: "17", title: "Лаборатория Интернет"}
]

export const $documentEnum = [
   {id: "90", title: "60/43_22/90"},
   {id: "88", title: "59/43_21"},
   {id: "86", title: "58"},
   {id: "84", title: "57"},
   {id: "80", title: "55"},
   {id: "78", title: "54"},
   {id: "76", title: "/53"},
   {id: "74", title: "/52"},
   {id: "72", title: "43_14//27"},
   {id: "70", title: "43_13//1"},
   {id: "66", title: "43_12/7"},
   {id: "64", title: "43_11/6"},
   {id: "62", title: "43_10/5"},
   {id: "60", title: "43_9/4"},
   {id: "58", title: "43_8/3"},
   {id: "56", title: "43_7/2"},
   {id: "54", title: "43_6/1"},
   {id: "42", title: "43_7/42"},
   {id: "34", title: "8"},
   {id: "32", title: "7"},
   {id: "30", title: "6"},
   {id: "28", title: "5"}
]

export const $contractorEnum = [
   {id: "874", title: "'7 Авеню'"},
   {id: "1128", title: "'Гора Белая', пос.Уралец, Горнолыжный курорт"},
   {id: "1102", title: "'Долина' (НУДО ДЮСШ 'РГШ-Кувандык')"},
   {id: "1124", title: "'ДонТур'"},
   {id: "1116", title: "'Каматрэвл'"},
   {id: "1108", title: "'Квань'"},
   {id: "1132", title: "'КРУИЗ'"},
   {id: "1544", title: "'ЛУКОМОРЬЕ' (Самарский Театр Кукол"},
   {id: "1094", title: "'Райдер' (АО Ильмен-Тау)"},
   {id: "1112", title: "'Свияжские холмы'"},
   {id: "1134", title: "'Такман', Пермский край, Горнолыжный курорт"},
   {id: "1088", title: "'Холдоми'(ООО Экстрим Сервис)"},
   {id: "1516", title: "'Экстрим Самара'"},
   {id: "750", title: "'Электроник-Дубрава' пансианат"},
   {id: "1502", title: "«ОГНИ ЗАРЕЧЬЯ» АО «КНПЗ»"},
   {id: "193", title: "20 Верст"},
   {id: "1522", title: "2Jump"},
   {id: "1532", title: "63 / УДИВИТЕЛЬНЫЕ ЭКСКУРСИИ"},
   {id: "788", title: "7 terrass"},
   {id: "1588", title: "Active Travel"},
   {id: "1562", title: "Art-Far-Took"},
   {id: "1524", title: "ATMOSFERA JUMP"},
   {id: "363", title: "Channel manager My Hotel"},
   {id: "1586", title: "CyberGame.club"},
   {id: "1118", title: "Cамарские пилигримы"},
   {id: "484", title: "Familia"},
   {id: "786", title: "Forel Fish"},
   {id: "1618", title: "Luxe"},
   {id: "1620", title: "My size"},
   {id: "1628", title: "OOO «Консолика»"},
   {id: "69", title: "Ost west Ост Вест (Самара)"},
   {id: "1212", title: "Ost-West Club Hotel (на visit-samara)"},
   {id: "365", title: "Primo Imperatore"},
   {id: "401", title: "Reserv (ООО 'Платформа Маркетинга')"},
   {id: "770", title: "Spa Асахи"},
   {id: "774", title: "Spa салон 'Бамбуки'"},
   {id: "1058", title: "Sweet Dreams"},
   {id: "1074", title: "Sweet Dreams (ИП Миронов)"},
   {id: "1076", title: "Sweet Dreams (ИП Миронов)"},
   {id: "1556", title: "Welcome Inn Самара"},
   {id: "1576", title: "Western Park"},
   {id: "83", title: "АВИАОТЕЛЬ (Самара)"},
   {id: "1416", title: "Агентство по организации праздников и мероприятий Фрукты,Самара"},
   {id: "474", title: "Аква Хаус база отдыха"},
   {id: "1560", title: "Аквариум студия"},
   {id: "265", title: "Аквилон (Новосиб)(Grand Leo)"},
   {id: "23", title: "Акиншина"},
   {id: "1072", title: "Актив Тайм"},
   {id: "1594", title: "Александр"},
   {id: "586", title: "Алые Паруса ЗК"}
]
